name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@1.0.0
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue appears stale as no activity has been seen for some time. We will close this issue in the next few days.'
        stale-pr-message: 'This PR appears stale as no activity has been seen for some time.  We will close this PR in the next few days.'
        stale-issue-label: 'Stale'
        stale-pr-label: 'Stale'
        days-before-stale: 10
        days-before-close: 3
